"""WZ encryption primitives.

Mirrors ``MapleLib/MapleCryptoLib`` and ``MapleLib/WzLib/Util/WzMutableKey.cs``.
A WZ key stream is generated by repeatedly AES-256-ECB encrypting the
4-byte region IV (repeated to fill a 16-byte block); strings and listWz
canvas data are XOR'd against that stream.
"""

from __future__ import annotations

from typing import Dict

from Crypto.Cipher import AES


# 4-byte IVs per region (from WzAESConstant.cs).
WZ_IV: Dict[str, bytes] = {
    "GMS": bytes([0x4D, 0x23, 0xC7, 0x2B]),
    "EMS": bytes([0xB9, 0x7D, 0x63, 0xE9]),
    "BMS": bytes([0x00, 0x00, 0x00, 0x00]),  # also CLASSIC / modern 64-bit
}

# Constant XOR'd into encrypted offsets.
WZ_OFFSET_CONSTANT = 0x581C3F6D

# 128-byte master key from MapleCryptoConstants.cs.
MAPLESTORY_USERKEY_DEFAULT = bytes([
    0x13, 0x00, 0x00, 0x00, 0x52, 0x00, 0x00, 0x00, 0x2A, 0x00, 0x00, 0x00, 0x5B, 0x00, 0x00, 0x00,
    0x08, 0x00, 0x00, 0x00, 0x02, 0x00, 0x00, 0x00, 0x10, 0x00, 0x00, 0x00, 0x60, 0x00, 0x00, 0x00,
    0x60, 0x00, 0x00, 0x00, 0x18, 0x00, 0x00, 0x00, 0xCB, 0x00, 0x00, 0x00, 0x05, 0x00, 0x00, 0x00,
    0x69, 0x00, 0x00, 0x00, 0x40, 0x00, 0x00, 0x00, 0x29, 0x00, 0x00, 0x00, 0x40, 0x00, 0x00, 0x00,
    0xC8, 0x00, 0x00, 0x00, 0x71, 0x00, 0x00, 0x00, 0x84, 0x00, 0x00, 0x00, 0x57, 0x00, 0x00, 0x00,
    0xCA, 0x00, 0x00, 0x00, 0x70, 0x00, 0x00, 0x00, 0x68, 0x00, 0x00, 0x00, 0x4C, 0x00, 0x00, 0x00,
    0x4F, 0x00, 0x00, 0x00, 0x10, 0x00, 0x00, 0x00, 0x09, 0x00, 0x00, 0x00, 0x76, 0x00, 0x00, 0x00,
    0x33, 0x00, 0x00, 0x00, 0x4F, 0x00, 0x00, 0x00, 0x18, 0x00, 0x00, 0x00, 0x86, 0x00, 0x00, 0x00,
])


def _trim_user_key(user_key: bytes) -> bytes:
    """Reduce the 128-byte UserKey to a 32-byte AES-256 key.

    Matches ``MapleCryptoConstants.GetTrimmedUserKey``: 8 source bytes at
    every 16th offset are scattered into ``key[i/4]``, leaving the other
    24 bytes zero (which is correct — the C# code does the same).
    """
    key = bytearray(32)
    for i in range(0, 128, 16):
        key[i // 4] = user_key[i]
    return bytes(key)


_AES_KEY = _trim_user_key(MAPLESTORY_USERKEY_DEFAULT)


class WzKey:
    """On-demand keystream derived from a region IV.

    For ``BMS``/``CLASSIC`` (all-zero IV) the keystream is also all zeros so
    XOR is a no-op — matching ``WzMutableKey.EnsureKeySize``.
    """

    __slots__ = ("_iv", "_data")

    def __init__(self, iv: bytes):
        if len(iv) != 4:
            raise ValueError("IV must be 4 bytes")
        self._iv = iv
        self._data = bytearray()

    @classmethod
    def for_region(cls, region: str) -> "WzKey":
        return cls(WZ_IV[region])

    def ensure(self, size: int) -> None:
        if size <= len(self._data):
            return
        # Round up to the next 16-byte block.
        target = (size + 15) & ~15
        if int.from_bytes(self._iv, "little") == 0:
            self._data = bytearray(target)
            return
        cipher = AES.new(_AES_KEY, AES.MODE_ECB)
        block = bytearray(16)
        out = bytearray(self._data)
        # Continue from where we left off.
        i = len(out)
        while i < target:
            if i == 0:
                for j in range(16):
                    block[j] = self._iv[j % 4]
            else:
                block[:] = out[i - 16:i]
            out += cipher.encrypt(bytes(block))
            i += 16
        self._data = out

    def __getitem__(self, index: int) -> int:
        if index >= len(self._data):
            self.ensure(index + 1)
        return self._data[index]

    def slice(self, length: int) -> bytes:
        self.ensure(length)
        return bytes(self._data[:length])


def compute_version_hash(version: int) -> int:
    """Compute the version hash from a MapleStory patch number."""
    h = 0
    for ch in str(version):
        h = (h * 32 + ord(ch) + 1) & 0xFFFFFFFF
    return h


def derive_version_check(version_hash: int) -> int:
    """Derive the encrypted version-check byte stored in the WZ header."""
    a = (version_hash >> 24) & 0xFF
    b = (version_hash >> 16) & 0xFF
    c = (version_hash >> 8) & 0xFF
    d = version_hash & 0xFF
    return (~(a ^ b ^ c ^ d)) & 0xFF
